"""
question_bank.py
────────────────
A structured fallback question bank with 130+ questions organized by category,
topic, and difficulty.

Used when:
  1. The LLM fails JSON validation after one retry.
  2. All LLM-generated candidates are detected as duplicates of existing questions.
  3. The deduplication pool is exhausted for a category.

Each entry is a dict:
  {
    "question_text": str,
    "category":      str,   # matches category weights keys
    "topic":         str,
    "difficulty":    str,   # easy | medium | hard
    "tags":          list[str]
  }
"""

from typing import List, Dict, Any

QUESTION_BANK: List[Dict[str, Any]] = [

    # ── RESUME / INTRODUCTION ─────────────────────────────────────────────────
    {"question_text": "Walk me through your background and what led you to software development.",
     "category": "Resume", "topic": "Introduction", "difficulty": "easy",
     "tags": ["intro", "background"]},
    {"question_text": "Which project in your portfolio are you most proud of and why?",
     "category": "Resume", "topic": "Projects", "difficulty": "easy",
     "tags": ["project", "portfolio"]},
    {"question_text": "Describe a technical challenge you solved that significantly impacted a project outcome.",
     "category": "Resume", "topic": "Problem Solving", "difficulty": "medium",
     "tags": ["challenge", "impact"]},
    {"question_text": "How has your experience evolved across the roles listed on your resume?",
     "category": "Resume", "topic": "Career Growth", "difficulty": "easy",
     "tags": ["career", "growth"]},
    {"question_text": "Which of your listed skills do you consider your strongest and how have you applied it?",
     "category": "Resume", "topic": "Skills", "difficulty": "easy",
     "tags": ["skills", "strength"]},
    {"question_text": "Tell me about a time you received critical feedback and how you responded to it.",
     "category": "Resume", "topic": "Self-Improvement", "difficulty": "medium",
     "tags": ["feedback", "growth"]},

    # ── PROJECT ───────────────────────────────────────────────────────────────
    {"question_text": "Explain the overall architecture of a significant project you have built.",
     "category": "Project", "topic": "Architecture", "difficulty": "medium",
     "tags": ["architecture", "design"]},
    {"question_text": "What was the most complex feature you implemented in a recent project? Walk me through the implementation.",
     "category": "Project", "topic": "Implementation", "difficulty": "hard",
     "tags": ["feature", "complexity"]},
    {"question_text": "How did you handle state management in your front-end project?",
     "category": "Project", "topic": "State Management", "difficulty": "medium",
     "tags": ["state", "frontend"]},
    {"question_text": "Describe how you implemented authentication and authorization in one of your projects.",
     "category": "Project", "topic": "Authentication", "difficulty": "medium",
     "tags": ["auth", "security"]},
    {"question_text": "If you could rebuild one of your projects from scratch, what would you do differently?",
     "category": "Project", "topic": "Retrospective", "difficulty": "medium",
     "tags": ["lessons", "design"]},
    {"question_text": "How did you ensure the performance and scalability of your project under load?",
     "category": "Project", "topic": "Performance", "difficulty": "hard",
     "tags": ["performance", "scalability"]},
    {"question_text": "Describe how you set up CI/CD for a project you worked on.",
     "category": "Project", "topic": "DevOps", "difficulty": "medium",
     "tags": ["ci/cd", "devops"]},
    {"question_text": "How did you approach testing in your last major project?",
     "category": "Project", "topic": "Testing", "difficulty": "medium",
     "tags": ["testing", "quality"]},

    # ── FRONTEND ──────────────────────────────────────────────────────────────
    {"question_text": "Explain the virtual DOM and why React uses it.",
     "category": "Frontend", "topic": "React", "difficulty": "easy",
     "tags": ["react", "dom"]},
    {"question_text": "What is the difference between controlled and uncontrolled components in React?",
     "category": "Frontend", "topic": "React", "difficulty": "easy",
     "tags": ["react", "forms"]},
    {"question_text": "How does React's reconciliation algorithm work?",
     "category": "Frontend", "topic": "React", "difficulty": "medium",
     "tags": ["react", "reconciliation"]},
    {"question_text": "Explain useEffect and when you would use it versus useMemo.",
     "category": "Frontend", "topic": "React Hooks", "difficulty": "medium",
     "tags": ["hooks", "react"]},
    {"question_text": "What are React Server Components and how do they differ from Client Components?",
     "category": "Frontend", "topic": "Next.js / React", "difficulty": "hard",
     "tags": ["nextjs", "rsc"]},
    {"question_text": "How does CSS specificity work? Explain with an example.",
     "category": "Frontend", "topic": "CSS", "difficulty": "easy",
     "tags": ["css", "specificity"]},
    {"question_text": "What is the difference between Flexbox and CSS Grid and when would you use each?",
     "category": "Frontend", "topic": "CSS Layout", "difficulty": "easy",
     "tags": ["css", "layout"]},
    {"question_text": "Explain event bubbling and event capturing in JavaScript.",
     "category": "Frontend", "topic": "JavaScript", "difficulty": "easy",
     "tags": ["js", "events"]},
    {"question_text": "What is a closure in JavaScript? Provide a real-world use case.",
     "category": "Frontend", "topic": "JavaScript", "difficulty": "medium",
     "tags": ["js", "closure"]},
    {"question_text": "Explain the JavaScript event loop, call stack, and microtask queue.",
     "category": "Frontend", "topic": "JavaScript Runtime", "difficulty": "medium",
     "tags": ["js", "event loop"]},
    {"question_text": "What are Promises and async/await? How do they relate to each other?",
     "category": "Frontend", "topic": "Async JavaScript", "difficulty": "easy",
     "tags": ["js", "async"]},
    {"question_text": "How would you optimize a slow-loading React application?",
     "category": "Frontend", "topic": "Performance", "difficulty": "hard",
     "tags": ["react", "performance"]},
    {"question_text": "Describe code splitting and lazy loading in React.",
     "category": "Frontend", "topic": "Performance", "difficulty": "medium",
     "tags": ["react", "lazy"]},
    {"question_text": "What is TypeScript and what advantages does it offer over plain JavaScript?",
     "category": "Frontend", "topic": "TypeScript", "difficulty": "easy",
     "tags": ["typescript", "types"]},
    {"question_text": "Explain TypeScript generics and provide a practical example.",
     "category": "Frontend", "topic": "TypeScript", "difficulty": "medium",
     "tags": ["typescript", "generics"]},
    {"question_text": "What are Web Workers and when would you use them?",
     "category": "Frontend", "topic": "Browser APIs", "difficulty": "hard",
     "tags": ["web workers", "browser"]},
    {"question_text": "Explain the critical rendering path and how it affects page performance.",
     "category": "Frontend", "topic": "Browser Performance", "difficulty": "hard",
     "tags": ["rendering", "performance"]},
    {"question_text": "What is CORS and how do you handle it in a web application?",
     "category": "Frontend", "topic": "HTTP / Security", "difficulty": "medium",
     "tags": ["cors", "http"]},

    # ── BACKEND ───────────────────────────────────────────────────────────────
    {"question_text": "Explain the REST architectural constraints and what makes an API truly RESTful.",
     "category": "Backend", "topic": "REST API", "difficulty": "easy",
     "tags": ["rest", "api"]},
    {"question_text": "What are the key differences between REST and GraphQL? When would you choose each?",
     "category": "Backend", "topic": "API Design", "difficulty": "medium",
     "tags": ["graphql", "rest"]},
    {"question_text": "How does JWT authentication work end to end?",
     "category": "Backend", "topic": "Authentication", "difficulty": "medium",
     "tags": ["jwt", "auth"]},
    {"question_text": "Explain OAuth 2.0 flow and the difference between authentication and authorization.",
     "category": "Backend", "topic": "Security", "difficulty": "medium",
     "tags": ["oauth", "auth"]},
    {"question_text": "What is middleware in the context of web frameworks like Express or FastAPI?",
     "category": "Backend", "topic": "Middleware", "difficulty": "easy",
     "tags": ["middleware", "express"]},
    {"question_text": "How do you handle rate limiting in a production API?",
     "category": "Backend", "topic": "Rate Limiting", "difficulty": "medium",
     "tags": ["rate limit", "api"]},
    {"question_text": "Explain the differences between synchronous and asynchronous programming in Node.js.",
     "category": "Backend", "topic": "Node.js", "difficulty": "medium",
     "tags": ["node", "async"]},
    {"question_text": "What is the N+1 query problem and how do you solve it?",
     "category": "Backend", "topic": "Performance", "difficulty": "medium",
     "tags": ["n+1", "database"]},
    {"question_text": "Describe how you would design a webhook system.",
     "category": "Backend", "topic": "Webhooks", "difficulty": "hard",
     "tags": ["webhook", "design"]},
    {"question_text": "What is the difference between horizontal and vertical scaling?",
     "category": "Backend", "topic": "Scalability", "difficulty": "easy",
     "tags": ["scaling", "architecture"]},
    {"question_text": "How does caching work in a backend system? Name different caching strategies.",
     "category": "Backend", "topic": "Caching", "difficulty": "medium",
     "tags": ["cache", "redis"]},
    {"question_text": "What is a message queue and when would you use RabbitMQ or Kafka over direct HTTP?",
     "category": "Backend", "topic": "Messaging", "difficulty": "hard",
     "tags": ["queue", "kafka"]},
    {"question_text": "Explain the Producer-Consumer pattern with a real-world backend use case.",
     "category": "Backend", "topic": "Patterns", "difficulty": "medium",
     "tags": ["producer", "consumer"]},
    {"question_text": "How do you implement pagination efficiently in a REST API?",
     "category": "Backend", "topic": "API Design", "difficulty": "medium",
     "tags": ["pagination", "rest"]},
    {"question_text": "Describe how you would handle file uploads at scale.",
     "category": "Backend", "topic": "File Handling", "difficulty": "hard",
     "tags": ["upload", "s3"]},

    # ── DATABASE ──────────────────────────────────────────────────────────────
    {"question_text": "What is database normalization? Explain 1NF, 2NF, and 3NF with examples.",
     "category": "Database", "topic": "Normalization", "difficulty": "medium",
     "tags": ["normalization", "sql"]},
    {"question_text": "Explain the difference between an inner join and a left outer join.",
     "category": "Database", "topic": "SQL Joins", "difficulty": "easy",
     "tags": ["sql", "joins"]},
    {"question_text": "What is an index in a database and how does it improve query performance?",
     "category": "Database", "topic": "Indexing", "difficulty": "easy",
     "tags": ["index", "performance"]},
    {"question_text": "What types of database indexes exist and when would you choose each?",
     "category": "Database", "topic": "Indexing", "difficulty": "medium",
     "tags": ["index", "btree", "hash"]},
    {"question_text": "Explain ACID properties and why they matter for transactional systems.",
     "category": "Database", "topic": "Transactions", "difficulty": "medium",
     "tags": ["acid", "transactions"]},
    {"question_text": "What is a deadlock? How do you detect and prevent it?",
     "category": "Database", "topic": "Concurrency", "difficulty": "hard",
     "tags": ["deadlock", "concurrency"]},
    {"question_text": "What is the difference between optimistic and pessimistic locking?",
     "category": "Database", "topic": "Concurrency", "difficulty": "hard",
     "tags": ["locking", "concurrency"]},
    {"question_text": "Explain the CAP theorem and how it affects distributed database design.",
     "category": "Database", "topic": "Distributed Systems", "difficulty": "hard",
     "tags": ["cap", "distributed"]},
    {"question_text": "What is database sharding and when would you implement it?",
     "category": "Database", "topic": "Scalability", "difficulty": "hard",
     "tags": ["sharding", "scaling"]},
    {"question_text": "Compare MongoDB and PostgreSQL. When would you choose NoSQL over relational?",
     "category": "Database", "topic": "Database Selection", "difficulty": "medium",
     "tags": ["mongodb", "postgres", "nosql"]},
    {"question_text": "Explain MongoDB's aggregation pipeline and give an example use case.",
     "category": "Database", "topic": "MongoDB", "difficulty": "medium",
     "tags": ["mongodb", "aggregation"]},
    {"question_text": "What is a connection pool and why is it important for production databases?",
     "category": "Database", "topic": "Performance", "difficulty": "medium",
     "tags": ["connection pool", "performance"]},
    {"question_text": "How do you optimize a slow SQL query? Walk me through your debugging process.",
     "category": "Database", "topic": "Query Optimization", "difficulty": "hard",
     "tags": ["sql", "optimization", "explain"]},
    {"question_text": "What is an ORM? What are its advantages and potential pitfalls?",
     "category": "Database", "topic": "ORM", "difficulty": "easy",
     "tags": ["orm", "sqlalchemy"]},

    # ── SYSTEM DESIGN ─────────────────────────────────────────────────────────
    {"question_text": "Design a URL shortener like bit.ly. Walk me through the architecture.",
     "category": "System Design", "topic": "URL Shortener", "difficulty": "medium",
     "tags": ["system design", "scalability"]},
    {"question_text": "Design a rate limiter for a public API that handles 1 million requests per day.",
     "category": "System Design", "topic": "Rate Limiter", "difficulty": "hard",
     "tags": ["rate limiter", "system design"]},
    {"question_text": "Design a notification system that supports push, email, and SMS at scale.",
     "category": "System Design", "topic": "Notification System", "difficulty": "hard",
     "tags": ["notifications", "system design"]},
    {"question_text": "How would you design a real-time chat application?",
     "category": "System Design", "topic": "Real-Time Systems", "difficulty": "hard",
     "tags": ["websocket", "chat", "system design"]},
    {"question_text": "Design a distributed job scheduler.",
     "category": "System Design", "topic": "Job Scheduler", "difficulty": "hard",
     "tags": ["scheduler", "distributed", "system design"]},
    {"question_text": "What are microservices and what problems do they solve compared to a monolith?",
     "category": "System Design", "topic": "Microservices", "difficulty": "medium",
     "tags": ["microservices", "monolith"]},
    {"question_text": "How does a CDN work and when would you use one?",
     "category": "System Design", "topic": "CDN", "difficulty": "easy",
     "tags": ["cdn", "performance"]},
    {"question_text": "Explain the circuit breaker pattern and when you would implement it.",
     "category": "System Design", "topic": "Resilience Patterns", "difficulty": "hard",
     "tags": ["circuit breaker", "resilience"]},
    {"question_text": "How would you design an e-commerce product search system?",
     "category": "System Design", "topic": "Search", "difficulty": "hard",
     "tags": ["search", "elasticsearch", "system design"]},
    {"question_text": "Explain eventual consistency and how you would handle it in a distributed system.",
     "category": "System Design", "topic": "Consistency", "difficulty": "hard",
     "tags": ["eventual consistency", "distributed"]},

    # ── SECURITY ──────────────────────────────────────────────────────────────
    {"question_text": "What is SQL injection? How do you prevent it?",
     "category": "Security", "topic": "SQL Injection", "difficulty": "easy",
     "tags": ["sql injection", "security"]},
    {"question_text": "Explain XSS and CSRF attacks and their mitigations.",
     "category": "Security", "topic": "Web Security", "difficulty": "medium",
     "tags": ["xss", "csrf", "security"]},
    {"question_text": "What is the difference between hashing, encryption, and encoding?",
     "category": "Security", "topic": "Cryptography", "difficulty": "easy",
     "tags": ["hashing", "encryption", "security"]},
    {"question_text": "How does HTTPS work and what does TLS add on top of HTTP?",
     "category": "Security", "topic": "HTTPS / TLS", "difficulty": "medium",
     "tags": ["https", "tls", "security"]},
    {"question_text": "What is the principle of least privilege and how do you apply it in software design?",
     "category": "Security", "topic": "Security Principles", "difficulty": "medium",
     "tags": ["least privilege", "security"]},
    {"question_text": "Describe how you would store user passwords securely.",
     "category": "Security", "topic": "Password Security", "difficulty": "easy",
     "tags": ["bcrypt", "passwords", "security"]},

    # ── DSA ───────────────────────────────────────────────────────────────────
    {"question_text": "Explain the time and space complexity of common sorting algorithms.",
     "category": "DSA", "topic": "Sorting", "difficulty": "medium",
     "tags": ["sorting", "complexity"]},
    {"question_text": "What is Big-O notation and why is it important?",
     "category": "DSA", "topic": "Complexity Analysis", "difficulty": "easy",
     "tags": ["big-o", "complexity"]},
    {"question_text": "Explain recursion and describe when to use it versus iteration.",
     "category": "DSA", "topic": "Recursion", "difficulty": "easy",
     "tags": ["recursion", "iteration"]},
    {"question_text": "What is dynamic programming? Give an example problem where it applies.",
     "category": "DSA", "topic": "Dynamic Programming", "difficulty": "hard",
     "tags": ["dp", "optimization"]},
    {"question_text": "Explain the difference between a stack and a queue. When do you use each?",
     "category": "DSA", "topic": "Data Structures", "difficulty": "easy",
     "tags": ["stack", "queue"]},
    {"question_text": "Describe how a hash map works internally, including collision resolution.",
     "category": "DSA", "topic": "Hash Maps", "difficulty": "medium",
     "tags": ["hash map", "collision"]},
    {"question_text": "Explain binary search and when it can be applied.",
     "category": "DSA", "topic": "Binary Search", "difficulty": "easy",
     "tags": ["binary search", "array"]},
    {"question_text": "What is a binary tree and how does DFS differ from BFS?",
     "category": "DSA", "topic": "Trees / Graphs", "difficulty": "medium",
     "tags": ["tree", "dfs", "bfs"]},
    {"question_text": "Explain graph traversal algorithms and real-world applications of each.",
     "category": "DSA", "topic": "Graphs", "difficulty": "medium",
     "tags": ["graph", "traversal"]},
    {"question_text": "What is a linked list and what are its advantages over arrays?",
     "category": "DSA", "topic": "Linked Lists", "difficulty": "easy",
     "tags": ["linked list", "data structure"]},
    {"question_text": "Explain the sliding window technique and give a problem where it applies.",
     "category": "DSA", "topic": "Sliding Window", "difficulty": "medium",
     "tags": ["sliding window", "array"]},
    {"question_text": "Describe the two-pointer technique with a concrete example.",
     "category": "DSA", "topic": "Two Pointers", "difficulty": "medium",
     "tags": ["two pointers", "array"]},

    # ── BEHAVIORAL ────────────────────────────────────────────────────────────
    {"question_text": "Describe a situation where you had to deal with a difficult team member. How did you handle it?",
     "category": "Behavioral", "topic": "Teamwork", "difficulty": "medium",
     "tags": ["teamwork", "conflict"]},
    {"question_text": "Tell me about a time you had to deliver a project under a tight deadline.",
     "category": "Behavioral", "topic": "Deadline Management", "difficulty": "medium",
     "tags": ["deadline", "pressure"]},
    {"question_text": "Describe a situation where you proactively identified and fixed a significant bug before it went to production.",
     "category": "Behavioral", "topic": "Problem Solving", "difficulty": "medium",
     "tags": ["proactive", "bug", "quality"]},
    {"question_text": "Give an example of a time you mentored or guided a less experienced team member.",
     "category": "Behavioral", "topic": "Leadership", "difficulty": "medium",
     "tags": ["mentoring", "leadership"]},
    {"question_text": "Describe a time you disagreed with a technical decision made by your team. How did you handle it?",
     "category": "Behavioral", "topic": "Technical Disagreement", "difficulty": "medium",
     "tags": ["disagreement", "communication"]},
    {"question_text": "Tell me about a time you had to quickly learn a new technology or framework to complete a task.",
     "category": "Behavioral", "topic": "Learning Agility", "difficulty": "easy",
     "tags": ["learning", "adaptability"]},
    {"question_text": "How do you prioritize tasks when you are handling multiple concurrent projects?",
     "category": "Behavioral", "topic": "Time Management", "difficulty": "medium",
     "tags": ["prioritization", "time management"]},

    # ── PROBLEM SOLVING ───────────────────────────────────────────────────────
    {"question_text": "Walk me through how you debug a production issue affecting thousands of users.",
     "category": "Problem Solving", "topic": "Debugging", "difficulty": "hard",
     "tags": ["debugging", "production"]},
    {"question_text": "How would you approach reducing the load time of a web application by 50%?",
     "category": "Problem Solving", "topic": "Performance Optimization", "difficulty": "hard",
     "tags": ["performance", "optimization"]},
    {"question_text": "Describe your process for investigating a sudden spike in API error rates.",
     "category": "Problem Solving", "topic": "Incident Response", "difficulty": "hard",
     "tags": ["incident", "monitoring"]},
    {"question_text": "How would you migrate a large legacy monolith to microservices with zero downtime?",
     "category": "Problem Solving", "topic": "Migration", "difficulty": "hard",
     "tags": ["migration", "microservices"]},
    {"question_text": "A critical service in your system is experiencing intermittent timeouts. How do you diagnose and fix it?",
     "category": "Problem Solving", "topic": "Debugging", "difficulty": "hard",
     "tags": ["timeout", "debugging", "distributed"]},
]


def get_questions_by_category(category: str) -> List[Dict[str, Any]]:
    """Return all questions for a given category."""
    return [q for q in QUESTION_BANK if q["category"].lower() == category.lower()]


def get_questions_by_difficulty(difficulty: str) -> List[Dict[str, Any]]:
    """Return all questions for a given difficulty level."""
    return [q for q in QUESTION_BANK if q["difficulty"].lower() == difficulty.lower()]


def get_questions_by_category_and_difficulty(category: str, difficulty: str) -> List[Dict[str, Any]]:
    """Return questions matching both category and difficulty."""
    return [
        q for q in QUESTION_BANK
        if q["category"].lower() == category.lower()
        and q["difficulty"].lower() == difficulty.lower()
    ]


def get_all_categories() -> List[str]:
    """Return unique list of categories in the bank."""
    return list({q["category"] for q in QUESTION_BANK})
